### ISSUE TITLE
CuckooSearch's runIteration is incompatible with other algorithms runIteration

### ISSUE THREAD

**Issue by karakatic** [NiaOrg/NiaPy#281]
CuckooSearch's runIteration is incompatible with other algorithms' runIteration. It is because of the required argument pa_v. This makes it impossible to use it in the experiments with generic method calls.

https://github.com/NiaOrg/NiaPy/blob/a135cc0c5f934fead21c72ee64aa8f67a09daa68/NiaPy/algorithms/basic/cs.py#L135

**Comment by karakatic** [comment]
To expand this issue: many NIA optimizers were changed in the latest version to extend the standard required arguments when calling runIteration. Earlier versions forced all the NIA parameter settings at the construction, not in the runIteration call... This change makes NiaPy unusable in other frameworks, where generic runIteration calls are made...

**Comment by sisco0** [comment]
Have a good day @karakatic . Would you recommend to move out these parameters to constructor function instead of being at the `runIteration` function?

**Comment by kb2623** [comment]
This parameter should not be and issue, because in `Algorithm` interface, method `runYield` unpacks the parameter as seen from:

https://github.com/NiaOrg/NiaPy/blob/a135cc0c5f934fead21c72ee64aa8f67a09daa68/NiaPy/algorithms/algorithm.py#L296

**Comment by zStupan** [comment]
IDEs report this as a problem because it seemingly goes against the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle) of object oriented programming. But it actually doesn't because of keyword arguments. Also, runIteration is essentially a private/protected method, I see no use case where you would need to call runIteration directly in your code.

In this particular case though, I don't think pa_v should be an additional parameter, because it stays the same through all iterations. It should just be set in the constructor/setParameters method. If it's optional there should be a flag in setParameters, something like `use_pa_v=True` and if it's true, self.pa should be set to `NP * pa`.

@karakatic Can you provide an example of this causing problems?

If it's an issue we would just need to change every algorithms `runIteration` to pop the additional parameters from `dparams` like I did in my BFOA implementation:
https://github.com/NiaOrg/NiaPy/blob/0fa51cb14215b645f9eead0e7182e92280700a9a/NiaPy/algorithms/basic/bfoa.py#L193-L214

We could also just do this to remove the warnings.

**Comment by firefly-cpp** [comment]
Fixed in #309 

@zStupan please post your solution (current status) and final comments before we close this issue.

**Comment by zStupan** [comment]
As I described in my previous comment, for the algorithms that had extra arguments in the run_iteration method, I removed them and popped them from the keyword arguments inside run_iteration.

In the case of CS, the pa_v parameter was actually static, it represents the number of nests abandoned each iteration i. e. pa * population_size, where pa is the probability of a nest being abandoned. So I just added an attribute self.num_abandoned in __init__ which stores that value so no additional parameters are actually needed.
