### ISSUE TITLE
NiaPy conda dependecy problem

### ISSUE THREAD

**Issue by lukapecnik** [NiaOrg/NiaPy#284]
**Steps to reproduce**
Include `NiaPy >= 2.0.0rc11` as a dependency to a Python package and deploy it to `conda` using GitHub workflow.

**Expected behavior**
NiaPy dependency should be found.

**Actual behavior**

![thumbnail_image](https://user-images.githubusercontent.com/23029992/101893016-6f205f80-3ba4-11eb-956f-ee58db2cf52e.png)

@GregaVrbancic could you please look into it? Is the `conda` version outdated?
Thank you.

Best regards,
l.

**Comment by GregaVrbancic** [comment]
Hi @lukapecnik,

the NiaPy conda package works just fine. I suppose you are trying to create a package for NiaAML? If so, you are having a problem with "conda-publish-action" from https://github.com/fcakyon/conda-publish-action which only supports the following channels:

- conda-forge
- pytorch
- fcakyon
- districtdatalabs

Since the NiaPy channel is not included, the dependency can not be resolved.

I would advise you to try and replace the mentioned action with this one: https://github.com/amauryval/publish_conda_package_action

This action allows you to manually specify the required conda channels. For the NiaPy package, you would probably need to add the following channel: "niaorg/label/rc". Please, do not take my word for this, as I did not test it myself.

**Comment by lukapecnik** [comment]
Hi @GregaVrbancic,

after following your instructions, I managed to deploy NiaAML to `conda`. The channel "niaorg/label/rc" was correct.
Thank you very much.

Best regards,
l.
