### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by zStupan** [NiaOrg/NiaPy#301]
Python 2.7 has reached end of life, and numpy stopped supporting it since numpy 1.17, I think we should do the same in NiaPy 2.0

Thoughts?

**Comment by firefly-cpp** [comment]
Good point! I totally support this idea?

@GregaVrbancic what about you?

**Comment by sisco0** [comment]
Hello, please take a look at my modified CI version.
I got rid of Python 2.7 and used Python 3.8 in Windows and Linux.
If that is ok I could create a pull request for it.
You could get an idea of the fork at this comment, where I also link my fork branch.
https://github.com/NiaOrg/NiaPy/issues/297#issuecomment-809100593

**Comment by GregaVrbancic** [comment]
Sure, we can drop the 2.7 support, this one is easy, but migration to the poetry package manager is a bit harder since all the scripts must be modified.

Regarding the testing versions of Python, in my opinion, we should test against all major versions. It is not the matter of who uses this package the most. On the other hand, we cannot be really sure that the academics really use the latest versions of Python. In my experience, it is quite the opposite, the academics tend to use older versions of Python.

**Comment by sisco0** [comment]
This issue could be closed with a32d6375b543f6d727b5ff15e697e593f3caf39b.
