### ISSUE TITLE
scipy dependency

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#303]
Hello everybody!

I made a very simple analysis of NiaPy dependencies. Since the beginning of the NiaPy framework development, dependencies were very systematically added to the base system according to the needs of package. @zStupan dropped the support
for Python 2.X versions which resulted in removal of some dependencies that were targetting only 2.X versions
of Python. That was the motivation that I checked the use of the other dependencies in NiaPy.

My first report here involves scipy package. Scipy was included from the beginning of this project mainly because of
support for Levy distribution.

Scipy components used in current release candidate of NiaPy:

| File        | Component         |
| ----------- | ------------------|
| fpa.py      | Gamma             |
| cs.py       | levy              |
| hho.py      | Gamma             |
| cs.py       | euclidean distance|
| gso.py      | euclidean distance|
| cro.py      | euclidean distance|
| aso.py      | euclidean distance|
| kh.py       | euclidean distance|
| de.py       | euclidean distance|
| cs.py       | levy              |

As we can see, only a few components of scipy are used in our framework. Therefore, I would like to suggest
that we try to remove scipy dependency in the following releases.

**Additional arguments for the removal of scipy dependency:**

- 10% of CI tests in the past failed, because of scipy problems
- some users reported installation problems of NiaPy due to the problems with scipy installation
- NiaPy should be simple and self-contained
- Dependency chain is smaller (useful for limited hardware)

**Solutions**

Euclidean distance can be implemented in separate file in utilities. Some other distances (Manhattan,...) may also join in the following releases.

Levy distributions can find a place in a new module. We may also consider the other distributions, e.g. chaotic maps [(Kent, Logistic...)](http://iztok-jr-fister.eu/static/publications/2.pdf) which were used a lot in different nature-inspired algorithms.

Comments are more than welcome!

**Comment by zStupan** [comment]
It could be done.
`scipy.special.gamma` can be replaced by `math.gamma` from the python standard library, since it's only used on numbers and not arrays. 
The levy function is already implemented here:
https://github.com/NiaOrg/NiaPy/blob/a32d6375b543f6d727b5ff15e697e593f3caf39b/NiaPy/algorithms/basic/hho.py#L116-L131
And repeated again here:
https://github.com/NiaOrg/NiaPy/blob/a32d6375b543f6d727b5ff15e697e593f3caf39b/NiaPy/algorithms/basic/fpa.py#L108-L115
This can be extracted to a utility function which would also be used in Cuckoo search instead of scipy.stats.levy. 

I suggest we remove the utility.py module and add these modules to the util package:

- distances.py (containing the euclidean distance and potentially others like manhattan distance)
- random.py (containing the levy flights function and possible other sampling methods)
- repair.py (containing limit repair functions currently in utility.py)
- array.py (containing objects2array and fullArray currently in utility.py)

**Comment by firefly-cpp** [comment]
Nice plan. @zStupan can we count on your help in solving this issue?

**Comment by zStupan** [comment]
I'm on it :smile:

**Comment by firefly-cpp** [comment]
Nice to hear this :)

**Comment by zStupan** [comment]
This issue can be closed now.

**Comment by firefly-cpp** [comment]
Resolved in #304
